#!/bin/bash

# Set errexit to exit immediately if a command exits with a non-zero status
set -o errexit

# Set nounset to exit if an unset variable is referenced
set -o nounset

# Remove existing celerybeat.pid file
rm -f './celerybeat.pid'


# Use Django management command to check migrations status
while true; do
    if python manage.py showmigrations --plan | grep "\[ \]" >/dev/null; then
        echo "Waiting for Django migrations to complete..."
        sleep 2
    else
        break
    fi
done


# Inform that Django migrations are completed
echo "Django migrations are completed"


# Execute watchfiles command with the following arguments:
# --filter python: Filter files for Python code
# celery.__main__.main: Run the celery main function
# --args '-A config.celery_app beat -l INFO': Pass additional arguments to the celery main function, specifying the celery app, beat mode, and log level INFO
exec python -m watchfiles --filter python celery.__main__.main --args '-A config.celery_app beat -l INFO'
