#!/usr/bin/env bash

### Create a database backup.
###
### Usage:
###     $ docker compose -f <environment>.yml (exec |run --rm) postgres backup

# Set shell options
set -o errexit    # Exit immediately if a command exits with a non-zero status
set -o pipefail   # Return a failure status if any command in a pipeline fails
set -o nounset    # Exit if an unset variable is referenced

# Define the directory where the script is located
working_dir="$(dirname ${0})"

# Source constant variables and functions
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

# Inform the user about the action being performed
message_welcome "Backing up the '${POSTGRES_DB}' database..."

# Check if backing up as 'postgres' user is attempted
if [[ "${POSTGRES_USER}" == "postgres" ]]; then
    message_error "Backing up as 'postgres' user is not supported. Assign 'POSTGRES_USER' env with another one and try again."
    exit 1
fi

# Set PostgreSQL environment variables
export PGHOST="${POSTGRES_HOST}"
export PGPORT="${POSTGRES_PORT}"
export PGUSER="${POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD}"
export PGDATABASE="${POSTGRES_DB}"

# Construct the backup filename with timestamp
backup_filename="${BACKUP_FILE_PREFIX}_$(date +'%Y_%m_%dT%H_%M_%S').sql.gz"

# Create a compressed SQL dump of the database and save it to the backup directory
pg_dump | gzip > "${BACKUP_DIR_PATH}/${backup_filename}"

# Inform the user about the successful creation of the backup
message_success "'${POSTGRES_DB}' database backup '${backup_filename}' has been created and placed in '${BACKUP_DIR_PATH}'."
