#!/usr/bin/env bash

### Remove a database backup.
###
### Parameters:
###     <1> filename of a backup to remove.
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) postgres rmbackup <1>

# Set shell options
set -o errexit    # Exit immediately if a command exits with a non-zero status
set -o pipefail   # Return a failure status if any command in a pipeline fails
set -o nounset    # Exit if an unset variable is referenced

# Define the directory where the script is located
working_dir="$(dirname ${0})"

# Source constant variables and functions
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

# Check if the backup filename is provided as an argument
if [[ -z ${1+x} ]]; then
    message_error "Backup filename is not specified yet it is a required parameter. Make sure you provide one and try again."
    exit 1
fi

# Construct the full path of the backup file
backup_filename="${BACKUP_DIR_PATH}/${1}"

# Check if the specified backup file exists
if [[ ! -f "${backup_filename}" ]]; then
    message_error "No backup with the specified filename found. Check out the 'backups' maintenance script output to see if there is one and try again."
    exit 1
fi

# Inform the user about the removal process
message_welcome "Removing the '${backup_filename}' backup file..."

# Remove the specified backup file
rm -r "${backup_filename}"

# Inform the user about the successful removal of the backup file
message_success "The '${backup_filename}' database backup has been removed."
